owner: honourandglory-admin
repo: upptime

sites:
  - name: Honour & Glory Website
    url: https://honour-and-glory-xi.vercel.app
  - name: H&G Blog
    url: https://honour-and-glory-xi.vercel.app/blog

status-website:
  baseUrl: /upptime
  logoUrl: https://honour-and-glory-xi.vercel.app/favicon.svg
  name: Honour & Glory Status
  introTitle: "**Honour & Glory Boxing Club** — site status and uptime."
  introMessage: Real-time uptime monitoring for our website, powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://honour-and-glory-xi.vercel.app
